name: coding_exercise

dependencies:
    - python>=3.6
    - jupyter
    - gdal>=2.3.0
    - libgdal>=2.3.0
    - numpy
    - scipy
    - matplotlib
    - pandas
    - requests
    - nbconvert
    - pandoc
    - texlive-core
    - jupyter_contrib_nbextensions
