name: coding_exercise

channels:
    - conda-forge
    - defaults

dependencies:
    - python>=3.6
    - jupyter
    - gdal<2.4
    - libgdal<2.4
    - numpy
    - scipy
    - matplotlib
    - pandas
    - nbconvert
    - pandoc
    - jupyter_contrib_nbextensions
